//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  reviews: Reviews;
  reviewsConnection: ReviewsConnection;
  dip: Dip;
  dipConnection: DipConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryReviewsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryReviewsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ReviewsFilter>;
};


export type QueryDipArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDipConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DipFilter>;
};

export type DocumentFilter = {
  reviews?: InputMaybe<ReviewsFilter>;
  dip?: InputMaybe<DipFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Reviews | Dip | Folder;

export type Reviews = Node & Document & {
  __typename?: 'Reviews';
  title: Scalars['String']['output'];
  type: Scalars['String']['output'];
  year: Scalars['Float']['output'];
  genre?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  rating: Scalars['Float']['output'];
  review?: Maybe<Scalars['String']['output']>;
  dateWatched?: Maybe<Scalars['String']['output']>;
  recommended?: Maybe<Scalars['Boolean']['output']>;
  status?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ReviewsFilter = {
  title?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  year?: InputMaybe<NumberFilter>;
  genre?: InputMaybe<StringFilter>;
  rating?: InputMaybe<NumberFilter>;
  review?: InputMaybe<StringFilter>;
  dateWatched?: InputMaybe<StringFilter>;
  recommended?: InputMaybe<BooleanFilter>;
  status?: InputMaybe<StringFilter>;
};

export type ReviewsConnectionEdges = {
  __typename?: 'ReviewsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Reviews>;
};

export type ReviewsConnection = Connection & {
  __typename?: 'ReviewsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ReviewsConnectionEdges>>>;
};

export type Dip = Node & Document & {
  __typename?: 'Dip';
  season: Scalars['Float']['output'];
  episode: Scalars['Float']['output'];
  title: Scalars['String']['output'];
  summary?: Maybe<Scalars['String']['output']>;
  method?: Maybe<Scalars['String']['output']>;
  motive?: Maybe<Scalars['String']['output']>;
  killer?: Maybe<Scalars['String']['output']>;
  notes?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  dateAdded?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DipFilter = {
  season?: InputMaybe<NumberFilter>;
  episode?: InputMaybe<NumberFilter>;
  title?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  method?: InputMaybe<StringFilter>;
  motive?: InputMaybe<StringFilter>;
  killer?: InputMaybe<StringFilter>;
  notes?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  dateAdded?: InputMaybe<StringFilter>;
};

export type DipConnectionEdges = {
  __typename?: 'DipConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Dip>;
};

export type DipConnection = Connection & {
  __typename?: 'DipConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DipConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateReviews: Reviews;
  createReviews: Reviews;
  updateDip: Dip;
  createDip: Dip;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateReviewsArgs = {
  relativePath: Scalars['String']['input'];
  params: ReviewsMutation;
};


export type MutationCreateReviewsArgs = {
  relativePath: Scalars['String']['input'];
  params: ReviewsMutation;
};


export type MutationUpdateDipArgs = {
  relativePath: Scalars['String']['input'];
  params: DipMutation;
};


export type MutationCreateDipArgs = {
  relativePath: Scalars['String']['input'];
  params: DipMutation;
};

export type DocumentUpdateMutation = {
  reviews?: InputMaybe<ReviewsMutation>;
  dip?: InputMaybe<DipMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  reviews?: InputMaybe<ReviewsMutation>;
  dip?: InputMaybe<DipMutation>;
};

export type ReviewsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['Float']['input']>;
  genre?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  rating?: InputMaybe<Scalars['Float']['input']>;
  review?: InputMaybe<Scalars['String']['input']>;
  dateWatched?: InputMaybe<Scalars['String']['input']>;
  recommended?: InputMaybe<Scalars['Boolean']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
};

export type DipMutation = {
  season?: InputMaybe<Scalars['Float']['input']>;
  episode?: InputMaybe<Scalars['Float']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  method?: InputMaybe<Scalars['String']['input']>;
  motive?: InputMaybe<Scalars['String']['input']>;
  killer?: InputMaybe<Scalars['String']['input']>;
  notes?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  dateAdded?: InputMaybe<Scalars['String']['input']>;
};

export type ReviewsPartsFragment = { __typename: 'Reviews', title: string, type: string, year: number, genre?: Array<string | null> | null, rating: number, review?: string | null, dateWatched?: string | null, recommended?: boolean | null, status?: string | null };

export type DipPartsFragment = { __typename: 'Dip', season: number, episode: number, title: string, summary?: string | null, method?: string | null, motive?: string | null, killer?: string | null, notes?: string | null, tags?: Array<string | null> | null, dateAdded?: string | null };

export type ReviewsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ReviewsQuery = { __typename?: 'Query', reviews: { __typename: 'Reviews', id: string, title: string, type: string, year: number, genre?: Array<string | null> | null, rating: number, review?: string | null, dateWatched?: string | null, recommended?: boolean | null, status?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ReviewsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ReviewsFilter>;
}>;


export type ReviewsConnectionQuery = { __typename?: 'Query', reviewsConnection: { __typename?: 'ReviewsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ReviewsConnectionEdges', cursor: string, node?: { __typename: 'Reviews', id: string, title: string, type: string, year: number, genre?: Array<string | null> | null, rating: number, review?: string | null, dateWatched?: string | null, recommended?: boolean | null, status?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type DipQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DipQuery = { __typename?: 'Query', dip: { __typename: 'Dip', id: string, season: number, episode: number, title: string, summary?: string | null, method?: string | null, motive?: string | null, killer?: string | null, notes?: string | null, tags?: Array<string | null> | null, dateAdded?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type DipConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DipFilter>;
}>;


export type DipConnectionQuery = { __typename?: 'Query', dipConnection: { __typename?: 'DipConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DipConnectionEdges', cursor: string, node?: { __typename: 'Dip', id: string, season: number, episode: number, title: string, summary?: string | null, method?: string | null, motive?: string | null, killer?: string | null, notes?: string | null, tags?: Array<string | null> | null, dateAdded?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const ReviewsPartsFragmentDoc = gql`
    fragment ReviewsParts on Reviews {
  __typename
  title
  type
  year
  genre
  rating
  review
  dateWatched
  recommended
  status
}
    `;
export const DipPartsFragmentDoc = gql`
    fragment DipParts on Dip {
  __typename
  season
  episode
  title
  summary
  method
  motive
  killer
  notes
  tags
  dateAdded
}
    `;
export const ReviewsDocument = gql`
    query reviews($relativePath: String!) {
  reviews(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ReviewsParts
  }
}
    ${ReviewsPartsFragmentDoc}`;
export const ReviewsConnectionDocument = gql`
    query reviewsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ReviewsFilter) {
  reviewsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ReviewsParts
      }
    }
  }
}
    ${ReviewsPartsFragmentDoc}`;
export const DipDocument = gql`
    query dip($relativePath: String!) {
  dip(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DipParts
  }
}
    ${DipPartsFragmentDoc}`;
export const DipConnectionDocument = gql`
    query dipConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DipFilter) {
  dipConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DipParts
      }
    }
  }
}
    ${DipPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      reviews(variables: ReviewsQueryVariables, options?: C): Promise<{data: ReviewsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewsQueryVariables, query: string}> {
        return requester<{data: ReviewsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewsQueryVariables, query: string}, ReviewsQueryVariables>(ReviewsDocument, variables, options);
      },
    reviewsConnection(variables?: ReviewsConnectionQueryVariables, options?: C): Promise<{data: ReviewsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewsConnectionQueryVariables, query: string}> {
        return requester<{data: ReviewsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewsConnectionQueryVariables, query: string}, ReviewsConnectionQueryVariables>(ReviewsConnectionDocument, variables, options);
      },
    dip(variables: DipQueryVariables, options?: C): Promise<{data: DipQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DipQueryVariables, query: string}> {
        return requester<{data: DipQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DipQueryVariables, query: string}, DipQueryVariables>(DipDocument, variables, options);
      },
    dipConnection(variables?: DipConnectionQueryVariables, options?: C): Promise<{data: DipConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DipConnectionQueryVariables, query: string}> {
        return requester<{data: DipConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DipConnectionQueryVariables, query: string}, DipConnectionQueryVariables>(DipConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  